services:
  node1:
    build: ./agent
    container_name: node1
    environment:
      - NODE_NAME=node1
      - PEERS=node2,node3
    networks:
      - cluster-net
    ports:
      - "5001:5000"

  node2:
    build: ./agent
    container_name: node2
    environment:
      - NODE_NAME=node2
      - PEERS=node1,node3
    networks:
      - cluster-net
    ports:
      - "5002:5000"

  node3:
    build: ./agent
    container_name: node3
    environment:
      - NODE_NAME=node3
      - PEERS=node1,node2
    networks:
      - cluster-net
    ports:
      - "5003:5000"

networks:
  cluster-net: