services:
  node1:
    build: ./agent
    container_name: node1
    environment:
      - NODE_NAME=node1
      - PEERS=node2,node3
    ports:
      - "5001:5000"
    volumes:
      - node1-data:/data
    networks:
      - cluster-net

  node2:
    build: ./agent
    container_name: node2
    environment:
      - NODE_NAME=node2
      - PEERS=node1,node3
    ports:
      - "5002:5000"
    volumes:
      - node2-data:/data
    networks:
      - cluster-net

  node3:
    build: ./agent
    container_name: node3
    environment:
      - NODE_NAME=node3
      - PEERS=node1,node2
    ports:
      - "5003:5000"
    volumes:
      - node3-data:/data
    networks:
      - cluster-net
  controller:
    build: ./controller
    container_name: controller
    ports:
      - "7000:7000"
    depends_on:
      - node1
      - node2
      - node3
    volumes:
      - controller-data:/app
    networks:
    - cluster-net

volumes:
  node1-data:
  node2-data:
  node3-data:
  controller-data:

  
networks:
  cluster-net:
    driver: bridge


