services:
  node1:
    build: .
    container_name: node1
    environment:
      - NODE_NAME=node1
      - PEERS=node2,node3
    volumes:
      - node1-data:/app
    networks:
      - cluster-net

  node2:
    build: .
    container_name: node2
    environment:
      - NODE_NAME=node2
      - PEERS=node1,node3
    volumes:
      - node2-data:/app
    networks:
      - cluster-net

  node3:
    build: .
    container_name: node3
    environment:
      - NODE_NAME=node3
      - PEERS=node1,node2
    volumes:
      - node3-data:/app
    networks:
      - cluster-net

volumes:
  node1-data:
  node2-data:
  node3-data:

  
networks:
  cluster-net:
    driver: bridge
